wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 128
digits:
  desc: null
  value: 5
hidden_size:
  desc: null
  value: 128
training_size:
  desc: null
  value: 50000
